# Generated by Django 4.2.5 on 2023-11-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melvins_treasure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='detalle_pedido',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedido', to='melvins_treasure.carrito'),
        ),
    ]
