# Generated by Django 4.2.5 on 2023-11-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('melvins_treasure', '0002_pedido_detalle_pedido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='detalle_pedido',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_pedido', to='melvins_treasure.carrito'),
        ),
    ]
